
 /**
  * This template file was generated by dynaTrace client.
  * The dynaTrace community portal can be found here: http://community.compuwareapm.com/
  * For information how to publish a plugin please visit http://community.compuwareapm.com/plugins/contribute/
  **/ 

package com.dynatrace.BT.Row;

import com.dynatrace.diagnostics.pdk.*;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.net.MalformedURLException;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Logger;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.*;


import javax.net.ssl.*;

import java.security.SecureRandom;
import java.security.cert.X509Certificate;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpressionException;
import javax.xml.xpath.XPathFactory;
import javax.xml.xpath.*;
import javax.xml.xpath.XPathVariableResolver;
import javax.xml.namespace.QName;

import org.apache.http.client.ClientProtocolException;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;


public class CounterMonitor implements Monitor {

	private static final Logger log = Logger.getLogger(CounterMonitor.class.getName());

	// measure constants
	private static final String METRIC_GROUP = "Row Counter";
	private static final String MSR_ROW = "Rows";

	//variables
	private Collection<MonitorMeasure>  measures  = null;
	private double rowCount = 0;
	private double uniqueRows;
	private double uniqueRowNum = 0;
	//private double storeCount;
	
	private URLConnection connection;
	private URL overviewurl;
	
	private String urlprotocol;
	private int urlport;
	private String dynaTraceURL;
	private String username;
	private String password;
	private String dashboardOption;
	
	private MonitorMeasure dynamicMeasure;
	private NodeList xpathNodeList;	
	private String split;
	

	@Override
	public Status setup(MonitorEnvironment env) throws Exception {
		
		log.finer("*****BEGIN PLUGIN LOGGING*****");
		log.finer("Entering setup method");
		log.finer("Entering variables from plugin.xml");
		
		urlprotocol = env.getConfigString("protocol");
		urlport = env.getConfigLong("httpPort").intValue();
		
		dynaTraceURL = env.getConfigString("dashboardURL");
		dynaTraceURL = dynaTraceURL.replaceAll(" ", "%20");
		if (!dynaTraceURL.startsWith("/"))
			dynaTraceURL = "/" + dynaTraceURL;
		
		username = env.getConfigString("username");
		password = env.getConfigPassword("password");

		log.finer("URL Protocol: " + urlprotocol);
		log.finer("URL Port: " + urlport);
		log.finer("dT URL: " + dynaTraceURL);
		log.finer("Username: " + username);
		
		dashboardOption = env.getConfigString("dashboardOption");
		log.finer("dashboardOption: " + dashboardOption);
		
		split = env.getConfigString("countChoice");
		
		log.finer("Exiting setup method");
		
		return new Status(Status.StatusCode.Success);
	}

	
	@Override
	public Status execute(MonitorEnvironment env) throws MalformedURLException{
		
		log.finer("Entering execute method");
		
		log.finer("Entering URL Setup");
		overviewurl = new URL(urlprotocol, env.getHost().getAddress(), urlport, dynaTraceURL);		
		
		log.finer("Executing URL: " + overviewurl.toString());
		
		try {
			
			//login to dynatrace server
			log.finer("Entering username/password setup");
			String userpass = username + ":" + password;
			String basicAuth = "Basic " + javax.xml.bind.DatatypeConverter.printBase64Binary(userpass.getBytes());
		
			disableCertificateValidation();
				
			//URL to grab XML file
			log.finer("Entering XML file grab");
			connection = overviewurl.openConnection();
			connection.setRequestProperty("Authorization", basicAuth);
			connection.setConnectTimeout(50000);

			InputStream responseIS = connection.getInputStream();	
			DocumentBuilderFactory xmlFactory = DocumentBuilderFactory.newInstance();
			DocumentBuilder docBuilder = xmlFactory.newDocumentBuilder();
			Document xmlDoc = docBuilder.parse(responseIS);
			XPathFactory xpathFact = XPathFactory.newInstance();
			XPath xpath = xpathFact.newXPath();

			//split statement to select code to execute based on user input for count
			log.finer("Entering splitting switch statement");
			int splitSwitch = 0;
			if (split.equals("count rows"))
				splitSwitch = 1;
			if (split.equals("count unique rows"))
				splitSwitch = 2;
			if (split.equals("count instances"))
				splitSwitch = 3;
			log.finer("splitSwitch: " + splitSwitch);
			

			//checks for splitting options
			switch (splitSwitch)
			{
				
				case 1: //"Count Rows"
					if (dashboardOption.equals("Business Transaction")) //if counting from Business Transaction
						rowCount = (Double) xpath.evaluate("count(/dashboardreport/data/businesstransactionsdashlet/transactions/transaction)",xmlDoc,XPathConstants.NUMBER);
						
					else if (dashboardOption.equals("Chart")) //if counting from Chart
						rowCount = (Double) xpath.evaluate("count(/dashboardreport/data/chartdashlet/measures/measure[not(contains(@measure, 'split by'))])",xmlDoc,XPathConstants.NUMBER);

					
					log.finer("Entering collectStaticMetrics method");
					
					//assign measure
					if ((measures = env.getMonitorMeasures(METRIC_GROUP, MSR_ROW)) != null) {
						for (MonitorMeasure measure : measures)
							measure.setValue(rowCount);
					}
				break;
				
				
				case 2: //"Count Unique Rows"
					
					log.finer("Entering split by Row");
					Set<String> uniqueRowSet = new HashSet<String>();  //used to store unique collector names
										
					
					if (dashboardOption.equals("Business Transaction")) //if counting Business Transaction
						xpathNodeList = (NodeList) xpath.evaluate("/dashboardreport/data/businesstransactionsdashlet/transactions/transaction", xmlDoc, XPathConstants.NODESET);
						
					else if (dashboardOption.equals("Chart"))	//if counting from Chart
						xpathNodeList = (NodeList) xpath.evaluate("/dashboardreport/data/chartdashlet/measures/measure[not(contains(@measure, 'split by'))]", xmlDoc, XPathConstants.NODESET);
											
					log.finer("Number of Unique xpathNodeList: " + xpathNodeList.getLength());
					
					
					if (xpathNodeList.getLength() < 1)
					{
						log.finer("xpathNodeList is less than 1");
						if ((measures = env.getMonitorMeasures(METRIC_GROUP, MSR_ROW)) != null) {
							for (MonitorMeasure measure : measures)
								measure.setValue(rowCount);
						}
					}
					
					//count number of unique rows
					else
					{
						for (int i = 0; i < xpathNodeList.getLength(); ++i){
							log.finer("i: " + i);
							
							if (dashboardOption.equals("Business Transaction")) //if counting from Business Transaction
								{
									String tempString = xpathNodeList.item(i).getAttributes().getNamedItem("group").toString();
									log.finer("tempString: " + tempString);
									String[] tempArray = tempString.replaceAll("\"","").replaceAll("group=","").split(";");
									log.finer("tempArray: " + tempArray[0]);
									uniqueRowSet.add(tempArray[0]);		
								}
							 
							else if (dashboardOption.equals("Chart"))  //if counting from Chart
								{
									String tempString = xpathNodeList.item(i).getAttributes().getNamedItem("measure").toString();
									log.finer("tempString: " + tempString);
									String[] tempArray = tempString.replaceAll("\"","").replaceAll("measure=","").split(",");
									log.finer("tempArray: " + tempArray[0]);
									uniqueRowSet.add(tempArray[0]);
								}

						}
					}

					rowCount = uniqueRowSet.size();	
					log.finer("Number of Unique Rows: " + uniqueRowSet.size());
					
					if ((measures = env.getMonitorMeasures(METRIC_GROUP, MSR_ROW)) != null) 
						for (MonitorMeasure measure : measures)
							measure.setValue(rowCount);
				
				break;
				
				
				case 3: //"Count instances per unique row"
				
					log.finer("Entering split by Row");
					
					//used to store rows with unique measures and their values
					Set<String> uniqueRowSetCase3 = new HashSet<String>();
					
					if (dashboardOption.equals("Business Transaction")) //if counting from Business Transaction
						xpathNodeList = (NodeList) xpath.evaluate("/dashboardreport/data/businesstransactionsdashlet/transactions/transaction", xmlDoc, XPathConstants.NODESET);
						
					else if (dashboardOption.equals("Chart"))	//if counting from Chart
						xpathNodeList = (NodeList) xpath.evaluate("/dashboardreport/data/chartdashlet/measures/measure[not(contains(@measure, 'split by'))]", xmlDoc, XPathConstants.NODESET);
						
					log.finer("Number of Unique xpathNodeList: " + xpathNodeList.getLength());
					
					//if no available metrics return 0
					if (xpathNodeList.getLength() < 1)
					{
						log.finer("xpathNodeList is less than 1");
						if ((measures = env.getMonitorMeasures(METRIC_GROUP, MSR_ROW)) != null) {
							for (MonitorMeasure measure : measures)
								measure.setValue(rowCount);
						}
					}
					
					//count number of unique rows
					else
					{
						for (int i = 0; i < xpathNodeList.getLength(); ++i){
							log.finer("i: " + i);
						
							if (dashboardOption.equals("Business Transaction")) //if counting Business Transaction
								{
									String tempString = xpathNodeList.item(i).getAttributes().getNamedItem("group").toString();
									log.finer("tempString: " + tempString);
									String[] tempArray = tempString.replaceAll("\"","").replaceAll("group=","").split(";");
									log.finer("tempArray: " + tempArray[0]);
									uniqueRowSetCase3.add(tempArray[0]);
								}
						
							else if (dashboardOption.equals("Chart"))
								{
									String tempString = xpathNodeList.item(i).getAttributes().getNamedItem("measure").toString();
									log.finer("tempString: " + tempString);
									String[] tempArray = tempString.replaceAll("\"","").replaceAll("measure=","").split(",");
									log.finer("tempArray: " + tempArray[0]);
									uniqueRowSetCase3.add(tempArray[0]);
								}
						}
					}	
					
					log.finer("Number of Unique Rows: " + uniqueRowSetCase3.size());
					
					String[] tempStringArray = uniqueRowSetCase3.toArray(new String[0]);
					
					log.finer("Entering split by all Rows");
					
					//loop through array of unique rows measure sets
					for (int j = 0; j < uniqueRowSetCase3.size(); ++j){
						log.finer("Splitting for Row: " + tempStringArray[j]);
						String tempString = tempStringArray[j];
						log.finer("Splitting for tempString: " + tempString);
						dynamicMetric(env, xpath, tempString, xmlDoc);
					}	
				break;
		}	
			
		
		} catch (ClientProtocolException e) {
			log.finer("ClientProtocolException: " + e);
			return new Status(Status.StatusCode.ErrorInternal);

		} catch (IOException e) {
			log.finer("IOException: " + e);
			return new Status(Status.StatusCode.ErrorInternal);

		} catch (Exception e){
			log.finer("Exception: " + e);
			return new Status(Status.StatusCode.ErrorInternal);
		}
		
		log.finer("Exiting execute method");
		log.finer("*****END PLUGIN LOGGING*****");
		
		return new Status(Status.StatusCode.Success);
	}
	
	
	
	private void dynamicMetric(MonitorEnvironment env, XPath xpath, String tempStringMeasure, Document xmlDoc) throws XPathExpressionException {
		
		log.finer("Entering dynamicMetrics method");
		
		//assign srign as a variable to use in xPath evaluate statement
		MapVariableResolver vr = new MapVariableResolver() ;
		vr.setVariable("myVar", tempStringMeasure);
		xpath.setXPathVariableResolver(vr);
		log.finer("myVar: " + vr.resolveVariable( new QName ("myVar")));
								
		//dynamic measure	
		if (dashboardOption.equals("Business Transaction")) //if counting from Business Transaction		
				uniqueRowNum = (Double) xpath.evaluate("count(/dashboardreport/data/businesstransactionsdashlet/transactions/transaction[contains(@group, $myVar)])", xmlDoc, XPathConstants.NUMBER);
						
		else if (dashboardOption.equals("Chart")) //if counting from Chart	
				uniqueRowNum = (Double) xpath.evaluate("count(/dashboardreport/data/chartdashlet/measures/measure[contains(@measure, $myVar)])", xmlDoc, XPathConstants.NUMBER);
		
		log.finer("uniqueRowNum: " + uniqueRowNum);
		log.finer("measures1: " + measures);
		
		{
			if ((measures = env.getMonitorMeasures(METRIC_GROUP, MSR_ROW)) != null) {
				for (MonitorMeasure measure : measures){
					log.finer("measures2: " + uniqueRowNum);
					dynamicMeasure = env.createDynamicMeasure(measure, "unique measure", tempStringMeasure);
					dynamicMeasure.setValue(uniqueRowNum);
				}								
			}
		}		
		log.finer("Exiting dynamicMetricsCollector method");
	}


	/**
	 * Shuts the Plugin down and frees resources. This method is called in the
	 * following cases:
	 * <ul>
	 * <li>the <tt>setup</tt> method failed</li>
	 * <li>the Plugin configuration has changed</li>
	 * <li>the execution duration of the Plugin exceeded the schedule timeout</li>
	 * <li>the schedule associated with this Plugin was removed</li>
	 * </ul>
	 *
	 * <p>
	 * The Plugin methods <tt>setup</tt>, <tt>execute</tt> and
	 * <tt>teardown</tt> are called on different threads, but they are called
	 * sequentially. This means that the execution of these methods does not
	 * overlap, they are executed one after the other.
	 *
	 * <p>
	 * Examples:
	 * <ul>
	 * <li><tt>setup</tt> (failed) -&gt; <tt>teardown</tt></li>
	 * <li><tt>execute</tt> starts, configuration changes, <tt>execute</tt>
	 * ends -&gt; <tt>teardown</tt><br>
	 * on next schedule interval: <tt>setup</tt> -&gt; <tt>execute</tt> ...</li>
	 * <li><tt>execute</tt> starts, execution duration timeout,
	 * <tt>execute</tt> stops -&gt; <tt>teardown</tt></li>
	 * <li><tt>execute</tt> starts, <tt>execute</tt> ends, schedule is
	 * removed -&gt; <tt>teardown</tt></li>
	 * </ul>
	 * Failed means that either an unhandled exception is thrown or the status
	 * returned by the method contains a non-success code.
	 *
	 *
	 * <p>
	 * All by the Plugin allocated resources should be freed in this method.
	 * Examples are opened sockets or files.
	 *
	 * @see Monitor#setup(MonitorEnvironment)
	 */	@Override
	public void teardown(MonitorEnvironment env) throws Exception {
		// TODO
	}
	
	public static void disableCertificateValidation() {
		
		log.finer("Entering disableCertificateValidation method");  
		
		// Create a trust manager that does not validate certificate chains
		  TrustManager[] trustAllCerts = new TrustManager[] { 
		    new X509TrustManager() {
		      public X509Certificate[] getAcceptedIssuers() { 
		        return new X509Certificate[0]; 
		      }
		      public void checkClientTrusted(X509Certificate[] certs, String authType) {}
		      public void checkServerTrusted(X509Certificate[] certs, String authType) {}
		  }};

		  // Ignore differences between given hostname and certificate hostname
		  HostnameVerifier hv = new HostnameVerifier() {
		    public boolean verify(String hostname, SSLSession session) { return true; }
		  };

		  // Install the all-trusting trust manager
		  try {
		    SSLContext sc = SSLContext.getInstance("SSL");
		    sc.init(null, trustAllCerts, new SecureRandom());
		    HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());
		    HttpsURLConnection.setDefaultHostnameVerifier(hv);
		  } catch (Exception e) {}
		  
		  log.finer("Leaving disableCertificateValidation method");
	}
}

